# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run lint
    - name: Set path for candle and light
      run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
    - run: npx electron-forge make --platform win32 --target squirrel
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
    - name: Create tag
      uses: rickstaa/action-create-tag@v1
      id: create-tag
      with:
        tag: latest
        tag_exists_error: false
        message: Latest release
    - name: Create release
      uses: actions/create-release@v1
      id: create-release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        draft: false
        prerelease: false
        release_name: "${{ steps.current-time.outputs.time }} - SHA: ${{ GITHUB.SHA }}"
    - name: Upload artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./out/make/squirrel.windows/x64/GPTray-1.0.0 Setup.exe
        asset_name: GPTray-Setup.exe
        asset_content_type: application/exe
